03_django/02_django_crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # NEW(GET) + CREATE(POST)
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'), # EDIT(GET) + UPDATE(POST)
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'), # DETAIL(GET) + CREATE(POST)
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete') # DETAIL(GET) + DELETE(POST)
]

03_django/02_django_crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jobs/', include('jobs.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 첫번째 인자(settings.MEDIA_URL) : 어떤 URL 을 정적으로 추가할지 (Media file url)
# 두번째 인자(document_root=) : 실제 해당 미디어 파일이 어디에 존재하는지

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

03_django/02_django_crud/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.index, name='index'),
    path('past_life/', views.past_life, name='past_life'),
]

03_django/02_django_crud/articles/models.py
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import Thumbnail
from django.urls import reverse
from django.db import models


def articles_image_path(instance, filename):
    return f'articles/{instance.pk}/iamges/{filename}'

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    # image = models.ImageField(blank=True)
    # image_thumbnail = ImageSpecField(
    #     source='image', # 원본 ImageField 이름
    #     processors=[Thumbnail(200, 300)],
    #     format='JPEG',
    #     options={'quality': 90},
    # )
    image = ProcessedImageField(
        # ProcessedImageField 에 인자로 들어가 있는 값들은 migrations 이후에
        # 추가되거나 수정되더라도 makemigrations 를 하지 않아도 된다.
        processors=[Thumbnail(200, 300)], # 처리할 작업 목록
        format='JPEG', # 저장 포맷
        options={'quality': 90}, # 추가 옵션들
        upload_to='articles/images', # 저장 위치 (MEDIA_ROOT/article/images)
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return f'/articles/{self.pk}/'
        # return reverse('articles:detail', args=[self.pk]) # /articles/10/
        return reverse('articles:detail', kwargs={'article_pk': self.pk}) # /articles/10/
        # 주의사항
        # reverse 함수에 args 랑 kwargs 를 동시에 인자로 보낼 수 없다.


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        # return self.
        return f'<Article({self.article_id}): Comment({self.pk})-{self.content}'

    

03_django/02_django_crud/jobs/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()

    def __str__(self):
        return self.name

03_django/02_django_crud/articles/views.py
from IPython import embed
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from .models import Article, Comment

# Create your views here.
def index(request):
    articles = Article.objects.order_by('-pk') # DB 가 변경
    # articles = Article.objects.all()[::-1] # python 이 변경
    
    context = {'articles': articles,}
    return render(request, 'articles/index.html', context)


def create(request):
    # CREATE
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        article = Article(title=title, content=content, image=image)
        article.save()
        # embed()
        return redirect(article) # detail
    # NEW
    else:
        return render(request, 'articles/create.html')


def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comments = article.comment_set.all()
    context = {'article': article, 'comments': comments,}
    return render(request, 'articles/detail.html', context)


def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect(article)


def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.image = request.FILES.get('image')
        article.save()
        return redirect(article)
    else:
        context = {'article': article,}
        return render(request, 'articles/update.html', context)


def comments_create(request, article_pk):
    # 댓글을 달 게시글
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        # form 에서 넘어온 댓글 정보
        content = request.POST.get('content')
        # 댓글 생성 및 저장
        comment = Comment(article=article, content=content)
        comment.save()
        return redirect(article)
        # return redirect('articles:detail' article.pk)
    else:
        return redirect(article)


def comments_delete(request, article_pk, comment_pk):
    # article = Article.objects.get(pk=article_pk)
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
    # return redirect(article)
    return redirect('articles:detail', article_pk)

03_django/02_django_crud/jobs/views.py
import requests
from pprint import pprint
from faker import Faker
from decouple import config
from django.shortcuts import render
from .models import Job

# Create your views here.
def index(request):
    return render(request, 'jobs/index.html')


def past_life(request):
    # 사용자로부터 이름 데이터를 받음.
    name = request.POST.get('name')

    # db 에 매칭되는 name 가져오기
    # Job.objects.get(name=name)
    # .get() 이 더 간단하지만 해당 값이 없을 경우 에러가 발생하기 때문.
    # filter : 한개던 0개던 상관없이 무조건 쿼리셋으로 가져옴.(리스트 형식)
    person = Job.objects.filter(name=name).first()
    
    # db 에 person 이 있는지 없는지 판단
    if person: # db 에 기존 이름이 있다면,
        past_job = person.past_job
    else: # db 에 기존 이름이 없다면(person 이 빈 쿼리셋(==False)))
        faker = Faker()
        past_job = faker.job()
        person = Job(name=name, past_job=past_job) # 새로운 레코드를 추가한다.
        person.save()
    
    # GIPHY (past_job 을  API 에 요청을 보내서 응답을 받음)
    GIPHY_API_KEY = config('GIPHY_API_KEY')
    url = f'http://api.giphy.com/v1/gifs/search?api_key={GIPHY_API_KEY}&q={past_job}&limit=1&rating=R'
    data = requests.get(url).json()
    try:
        image = data.get('data')[0].get('images').get('original').get('url')
    except IndexError:
        image = None


    context = {'person': person, 'image': image,}
    return render(request, 'jobs/past_life.html', context)

03_django/02_django_crud/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <img src="{% static 'images/sk.png' %}" alt="sample_img">
  <h1 class="text-center">CREATE</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title" required><br>
    <label for="content">CONTENT</label>
    <textarea name="content" id="content" cols="30" rows="5"></textarea><br>
    <label for="image">IMAGE</label>
    <input type="file" name="image" id="image" accept="image/*">
    <input type="submit" value="submit">
  </form>
{% endblock %}

03_django/02_django_crud/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <img src="{{ article.image_thumbnail.url }}" alt="thumbnail">
  
  <h1 class="text-center">DETAIL</h1>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% else %}
    <img src="{% static 'articles/images/no.png' %}" alt="no_img">
  {% endif %}
  <h2>{{ article.pk }} 번째 글</h2>
  <hr>
  <p>제목: {{ article.title }}</p>
  <p>내용: {{ article.content }}</p>
  <p>작성 시각: {{ article.created_at }}</p>
  <p>수정 시각: {{ article.updated_at }}</p>
  <hr>
  <!-- 댓글 출력 -->
  <p><b>{{ comments|length }}개의 댓글</b></p>
  {% for comment in comments %}
    <li>
      {{ comment.content }}
      <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <input type="submit" value="DELETE">
      </form>
    </li>
  {% empty %}
    <p><b>댓글이 없어요..</b></p>
  {% endfor %}
  <hr>
  <!-- 댓글 작성 form -->
  <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="content">COMMENT</label>
    <input type="text" name="content" id="content">
    <input type="submit" value="submit">
  </form>
  <hr>
  <a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('진짜 지울거야??')">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock %}

03_django/02_django_crud/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <img src="{% static 'articles/images/ss.png' %}" alt="sample_img">
  <h1 class="text-center">Articles</h1>
  <a href="{% url 'articles:create' %}">[NEW]</a>
  <hr>
  {% for article in articles %}
    <p>글 번호: {{ article.pk }}</p>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <a href="{{ article.get_absolute_url }}">[DETAIL]</a>
    <hr>
  {% endfor %}
{% endblock %}

03_django/02_django_crud/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1 class="text-center">UPDATE</h1>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="sample">
  {% else %}
    <img src="{% static 'articles/images/no.png' %}" alt="no_img">
  {% endif %}
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title" value="{{ article.title }}"><br>
    <label for="content">CONTENT</label>
    <textarea name="content" id="content" cols="30" rows="5">{{ article.content }}</textarea><br>
    <label for="image">IMAGE</label>
    <input type="file" name="image" id="image" accept="image/*"><br>
    <input type="submit" value="submit">
  </form>
  <a href="{{ article.get_absolute_url }}">[back]</a>
{% endblock %}

03_django/02_django_crud/crud/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="shortcut icon" href="{% static 'articles/favicon/cube.png' %}">
  <title>Document</title>
</head>

<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
</body>

</html>

03_django/02_django_crud/jobs/templates/jobs/index.html
{% extends 'base.html' %}
{% block content %}
<h1>전생의 직업</h1>
<p>당신의 전생의 직업을 알려드립니다..</p>

<form action="{% url 'jobs:past_life' %}" method="POST">
  {% csrf_token %}
  <label for="name">NAME</label>
  <input type="text" name="name" id="name">
  <input type="submit" value="submit">
</form>
{% endblock %}

03_django/02_django_crud/jobs/templates/jobs/past_life.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ person.name }} 님의 전생은 {{ person.past_job }}입니다.</h1>
<img src="{{ image }}" alt="gif_img">


<a href="{% url 'jobs:index' %}">다시하기</a>
{% endblock %}